require: rubocop-rspec

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

#### RSpec rules to turn off

RSpec/ExpectChange:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 15
